version: 2.1 # use CircleCI 2.1
dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    parallelism: 10
    working_directory: ~/Adrestus # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/openjdk:11-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
        - checkout # check out source code to working directory
        - run: |
            ./mvnw \
            -Dtest=$(for file in $(circleci tests glob "src/test/**/**.java" \
            | circleci tests split --split-by=timings); \
            do basename $file \
            | sed -e "s/.java/,/"; \
            done | tr -d '\r\n') \
            -e test
        - store_test_results: # We use this timing data to optimize the future runs
           path: target/surefire-reports
        - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
            keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
        - run: mvn dependency:go-offline # gets the project dependencies
        - save_cache: # saves the project dependencies
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
        - run: mvn clean install -U
workflows: # The following yaml will schedule this maven build operation to run every day at 12:00am UTC
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master      
    jobs:
      - build

build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build