package io.Adrestus.core.BlockPipeline;

public enum BlockRequestType {
    FORGE_DIFFICULTY_BUILDER("FORGE_DIFFICULTY_BUILDER"),
    FORGE_INITIALIZER_BUILDER("FORGE_INITIALIZER_BUILDER"),
    FORGE_SERIALIZER_BLOCK("FORGE_SERIALIZER_BLOCK"),
    FORGE_STAKING_MAP_BUILDER("FORGE_STAKING_MAP_BUILDER"),
    FORGE_STRUCTURE_MAP_BUILDER("FORGE_STRUCTURE_MAP_BUILDER"),
    FORGE_VALIDATORS_ASSIGN_BUILDER("FORGE_VALIDATORS_ASSIGN_BUILDER"),
    FORGE_DIFFERENT_ORIGIN_BUILDER("FORGE_DIFFERENT_ORIGIN_BUILDER"),
    FORGE_FEE_REWARD_BUILDER("FORGE_FEE_REWARD_BUILDER"),
    FORGE_INBOUND_BUILDER("FORGE_INBOUND_BUILDER"),
    FORGE_OUTBOUND_BUILDER("FORGE_OUTBOUND_BUILDER"),
    FORGE_PATRICIA_TREE_BUILDER("FORGE_PATRICIA_TREE_BUILDER"),
    FORGE_SERIALIZER_BLOCK_BUILDER("FORGE_SERIALIZER_BLOCK_BUILDER"),
    INVENT_CACHE_BUILDER("INVENT_CACHE_BUILDER"),
    INVENT_DATABASE_STORAGE_BUILDER("INVENT_DATABASE_STORAGE_BUILDER"),
    INVENT_INBOUND_BUILDER("INVENT_INBOUND_BUILDER"),
    INVENT_OUTBOUND_BUILDER("INVENT_OUTBOUND_BUILDER"),
    INVENT_INITIALIZER_BUILDER("INVENT_INITIALIZER_BUILDER"),
    INVENT_REWARDS_BUILDER("INVENT_REWARDS_BUILDER"),
    INVENT_TREE_POOL_BUILDER("INVENT_TREE_POOL_BUILDER"),
    INVENT_SYNC_BLOCKS_BUILDER("INVENT_SYNC_BLOCKS_BUILDER"),
    INVENT_TRX_DIFFERENT_ORIGIN_BUILDER("INVENT_TRX_DIFFERENT_ORIGIN_BUILDER("),
    INVENT_RECAP_DIFFERENT_ORIGIN_BUILDER("INVENTRECAPDIFFERENTORIGINBUILDER");
    private final String title;

    BlockRequestType(String title) {
        this.title = title;
    }
}
